

export const CATEGORIES = ['All', 'Tech', 'Core Engineering', 'Business & Analytics', 'Design', 'Marketing & HR'];

export const JOBS = [
  {
    id: 'j01', category: 'Tech', featured: true, isNew: false,
    title: 'Web Developer Intern', company: 'Google', companySize: 'MNC',
    industry: 'Internet / Technology', difficulty: 'Medium',
    tags: ['#frontend', '#remote', '#react', '#javascript'],
    companyInfo: 'Google LLC is a multinational technology company. This role is within the Core Web team building products used by billions.',
    location: 'Bangalore, India', branch: ['CSE', 'IT'], stipend: 20000, salaryType: 'stipend',
    type: 'Remote', deadline: '2026-05-10', quota: 8, duration: '3 months',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    keywords: ['web', 'frontend', 'html', 'css', 'javascript', 'react', 'developer', 'ui'],
    description: 'Join the Google Frontend team to build responsive, accessible web interfaces used by billions. Work directly with senior engineers on real production features.',
    responsibilities: ['Build responsive UI components using React and modern CSS', 'Collaborate with UX designers to implement pixel-perfect designs', 'Write clean, tested, and documented code', 'Participate in code reviews and sprint planning', 'Identify and fix performance bottlenecks'],
    perks: ['Laptop provided', 'Flexible hours', 'Certificate of completion', 'PPO possibility', 'LinkedIn recommendation'],
  },
  {
    id: 'j02', category: 'Tech', featured: true, isNew: false,
    title: 'Backend Developer Intern', company: 'Amazon', companySize: 'MNC',
    industry: 'E-commerce / Cloud', difficulty: 'Hard',
    tags: ['#backend', '#onsite', '#aws', '#python'],
    companyInfo: 'Amazon is a global leader in e-commerce and cloud computing. This internship is under Amazon Web Services focused on distributed systems.',
    location: 'Hyderabad, India', branch: ['CSE', 'IT'], stipend: 22000, salaryType: 'stipend',
    type: 'Onsite', deadline: '2026-05-15', quota: 5, duration: '3 months',
    skills: ['Node.js', 'Python', 'SQL', 'REST APIs', 'AWS'],
    keywords: ['backend', 'server', 'api', 'node', 'python', 'sql', 'database', 'aws'],
    description: 'Work with Amazon distributed backend teams to design and implement scalable microservices powering millions of daily transactions.',
    responsibilities: ['Design and implement RESTful APIs', 'Write database schemas and optimise SQL/NoSQL queries', 'Deploy services on AWS (EC2, Lambda, DynamoDB)', 'Write unit and integration tests', 'Participate in architecture discussions'],
    perks: ['Relocation support', 'Meals provided', 'PPO possibility', 'AWS certification sponsorship', 'Senior SDE mentorship'],
  },
  {
    id: 'j03', category: 'Business & Analytics', featured: false, isNew: true,
    title: 'Data Analyst Intern', company: 'Microsoft', companySize: 'MNC',
    industry: 'Software / SaaS', difficulty: 'Easy',
    tags: ['#data', '#hybrid', '#powerbi', '#sql'],
    companyInfo: 'Microsoft is a global technology company. This role is within the Power BI product team in Noida.',
    location: 'Noida, India', branch: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'Electrical', 'Any'], stipend: 15000, salaryType: 'stipend',
    type: 'Hybrid', deadline: '2026-05-20', quota: 10, duration: '2 months',
    skills: ['Python', 'Excel', 'SQL', 'Power BI', 'Statistics'],
    keywords: ['data', 'analytics', 'analyst', 'excel', 'powerbi', 'sql', 'python', 'visualization'],
    description: 'Analyse product usage data to surface actionable insights that directly influence the Power BI roadmap.',
    responsibilities: ['Query large datasets using SQL and Python', 'Build interactive dashboards in Power BI', 'Conduct A/B test analysis', 'Prepare weekly data reports', 'Identify trends and growth opportunities'],
    perks: ['Hybrid schedule', 'Microsoft 365 access', 'Certificate', 'Possible return offer', 'Networking events'],
  },
  {
    id: 'j04', category: 'Tech', featured: true, isNew: false,
    title: 'Machine Learning Intern', company: 'IBM', companySize: 'MNC',
    industry: 'AI / Research', difficulty: 'Hard',
    tags: ['#ml', '#remote', '#python', '#ai'],
    companyInfo: 'IBM Research is one of the world largest industrial research organisations. This internship is within IBM Watson AI division.',
    location: 'Bangalore, India', branch: ['CSE', 'IT', 'AI'], stipend: 25000, salaryType: 'stipend',
    type: 'Remote', deadline: '2026-04-30', quota: 4, duration: '4 months',
    skills: ['Python', 'TensorFlow', 'Scikit-learn', 'NumPy', 'Pandas'],
    keywords: ['ml', 'ai', 'machine learning', 'tensorflow', 'pytorch', 'sklearn', 'deep learning', 'nlp'],
    description: 'Develop, train, and evaluate machine learning models for IBM Watson services on real NLP and computer vision problems.',
    responsibilities: ['Train and fine-tune ML models using TensorFlow/PyTorch', 'Conduct experiments and track metrics', 'Clean and preprocess large real-world datasets', 'Document methodology in internal reports', 'Present results in weekly reviews'],
    perks: ['Fully remote', 'IBM Research credit', 'Research paper opportunity', 'Highest stipend in cohort', 'Global team exposure'],
  },
  {
    id: 'j05', category: 'Core Engineering', featured: false, isNew: false,
    title: 'Mechanical Design Intern', company: 'Tata Motors', companySize: 'MNC',
    industry: 'Automotive / EV', difficulty: 'Medium',
    tags: ['#mechanical', '#onsite', '#cad', '#ev'],
    companyInfo: 'Tata Motors is India largest automobile manufacturer. This internship is in the EV design division.',
    location: 'Pune, India', branch: ['Mechanical'], stipend: 12000, salaryType: 'stipend',
    type: 'Onsite', deadline: '2026-05-25', quota: 6, duration: '3 months',
    skills: ['AutoCAD', 'SolidWorks', 'CATIA', 'FEA', 'GD&T'],
    keywords: ['mechanical', 'design', 'autocad', 'solidworks', 'catia', 'cad', 'manufacturing'],
    description: 'Assist in the design and prototyping of EV body and chassis components using industry-grade CAD tools.',
    responsibilities: ['Create 3D models and drawings using CATIA/SolidWorks', 'Run FEA simulations', 'Work with manufacturing teams for design feasibility', 'Participate in design reviews', 'Support prototype builds in the workshop'],
    perks: ['Workshop access', 'PPE provided', 'Certificate', 'Factory tours', 'Accommodation support'],
  },
  {
    id: 'j06', category: 'Core Engineering', featured: false, isNew: false,
    title: 'Electrical Engineer Intern', company: 'L&T', companySize: 'MNC',
    industry: 'Infrastructure / Power', difficulty: 'Medium',
    tags: ['#electrical', '#onsite', '#plc', '#power'],
    companyInfo: 'Larsen and Toubro is a major engineering and construction conglomerate. Role is in the Power Systems division.',
    location: 'Mumbai, India', branch: ['Electrical', 'ECE'], stipend: 14000, salaryType: 'stipend',
    type: 'Onsite', deadline: '2026-05-18', quota: 7, duration: '3 months',
    skills: ['MATLAB', 'PLC', 'Circuit Design', 'AutoCAD Electrical', 'Power Systems'],
    keywords: ['electrical', 'power', 'circuit', 'plc', 'matlab', 'control', 'electronics'],
    description: 'Support the L&T Power Systems team on live infrastructure projects involving substation design and PLC programming.',
    responsibilities: ['Prepare single-line diagrams using AutoCAD Electrical', 'Program and test PLCs for industrial automation', 'Conduct load flow analysis using MATLAB', 'Visit live construction sites', 'Prepare equipment specifications'],
    perks: ['Site visits', 'Safety training', 'Certificate', 'Industry exposure', 'Referral letter'],
  },
  {
    id: 'j07', category: 'Design', featured: false, isNew: true,
    title: 'UI/UX Designer Intern', company: 'Adobe', companySize: 'MNC',
    industry: 'Creative Software', difficulty: 'Medium',
    tags: ['#design', '#remote', '#figma', '#ux'],
    companyInfo: 'Adobe Inc. is the world leader in creative software. This role is in the Experience Design team for Adobe Creative Cloud.',
    location: 'Noida, India', branch: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'Electrical', 'Any'], stipend: 18000, salaryType: 'stipend',
    type: 'Remote', deadline: '2026-06-01', quota: 6, duration: '3 months',
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'Design Systems'],
    keywords: ['ui', 'ux', 'design', 'figma', 'adobe', 'prototype', 'wireframe', 'user experience'],
    description: 'Design intuitive experiences for Adobe Creative Cloud products used by 30M+ professionals. Own design flows from user research to high-fidelity prototypes.',
    responsibilities: ['Create wireframes and high-fidelity mockups in Figma', 'Conduct user interviews and usability testing', 'Maintain and extend the Adobe Design System', 'Collaborate with PMs and frontend engineers', 'Present design decisions to stakeholders'],
    perks: ['Adobe Creative Cloud free access', 'Remote work', 'Design critique sessions', 'Portfolio-worthy work', 'PPO possibility'],
  },
  {
    id: 'j08', category: 'Marketing & HR', featured: false, isNew: false,
    title: 'Digital Marketing Intern', company: 'Flipkart', companySize: 'MNC',
    industry: 'E-commerce', difficulty: 'Easy',
    tags: ['#marketing', '#remote', '#seo', '#growth'],
    companyInfo: 'Flipkart is India largest e-commerce marketplace. This internship is within the Growth Marketing team.',
    location: 'Bangalore, India', branch: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'Electrical', 'Any'], stipend: 10000, salaryType: 'stipend',
    type: 'Remote', deadline: '2026-05-05', quota: 12, duration: '2 months',
    skills: ['SEO', 'Google Analytics', 'Content Writing', 'Social Media', 'Email Marketing'],
    keywords: ['marketing', 'seo', 'content', 'social', 'analytics', 'digital', 'campaign', 'ads'],
    description: 'Plan, execute, and optimise digital marketing campaigns across paid and organic channels to drive user growth.',
    responsibilities: ['Run Google Ads and Meta Ads campaigns', 'Track performance via Google Analytics', 'Write SEO-optimised content', 'Manage social media accounts', 'A/B test email campaigns'],
    perks: ['Fully remote', 'Ad budget exposure', 'Real campaign ownership', 'Marketing tool access', 'Certificate'],
  },
  {
    id: 'j09', category: 'Business & Analytics', featured: false, isNew: false,
    title: 'Business Analyst Intern', company: 'Deloitte', companySize: 'MNC',
    industry: 'Consulting', difficulty: 'Medium',
    tags: ['#consulting', '#hybrid', '#excel', '#strategy'],
    companyInfo: 'Deloitte is one of the Big Four professional services firms. This internship is within the Strategy and Analytics consulting practice.',
    location: 'Gurgaon, India', branch: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'Electrical', 'Any'], stipend: 16000, salaryType: 'stipend',
    type: 'Hybrid', deadline: '2026-05-12', quota: 8, duration: '3 months',
    skills: ['Excel', 'PowerPoint', 'SQL', 'Requirements Gathering', 'Process Mapping'],
    keywords: ['business', 'analysis', 'analyst', 'excel', 'consulting', 'requirement', 'process'],
    description: 'Work alongside Deloitte consultants on real client engagements, analysing business processes and building data models.',
    responsibilities: ['Gather and document functional requirements', 'Build process flow maps using BPMN', 'Analyse datasets in Excel/SQL', 'Prepare client-ready PowerPoint presentations', 'Participate in client meetings'],
    perks: ['Consulting exposure', 'Client site visits', 'Big 4 certificate', 'LinkedIn endorsement', 'Possible full-time offer'],
  },
  {
    id: 'j10', category: 'Marketing & HR', featured: false, isNew: false,
    title: 'HR Intern', company: 'Infosys', companySize: 'MNC',
    industry: 'IT Services', difficulty: 'Easy',
    tags: ['#hr', '#onsite', '#recruitment', '#people'],
    companyInfo: 'Infosys is a global leader in IT consulting with 300,000+ employees. Role is in Talent Acquisition and Learning and Development.',
    location: 'Mysore, India', branch: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'Electrical', 'Any'], stipend: 9000, salaryType: 'stipend',
    type: 'Onsite', deadline: '2026-05-08', quota: 15, duration: '2 months',
    skills: ['Communication', 'MS Office', 'Recruitment', 'HR Policies', 'Onboarding'],
    keywords: ['hr', 'human resources', 'recruitment', 'talent', 'hiring', 'onboarding'],
    description: 'Join Infosys HR team to assist with campus recruitment drives, employee onboarding, and L&D programmes at the Mysore campus.',
    responsibilities: ['Coordinate and schedule interviews', 'Manage onboarding documentation', 'Assist with L&D workshops', 'Maintain HRMS records', 'Support performance review cycles'],
    perks: ['Infosys campus experience', 'HR professional network', 'Certificate', 'Accommodation facility', 'Return offer possibility'],
  },
];

export const BRANCHES = ['Any', 'CSE', 'IT', 'ECE', 'Mechanical', 'Electrical', 'Civil', 'AI'];
export const TYPES = ['All', 'Remote', 'Onsite', 'Hybrid'];

export const PIPELINE_STAGES = [
  { key: 'pending',     label: 'Pending'     },
  { key: 'shortlisted', label: 'Shortlisted' },
  { key: 'interview',   label: 'Interview'   },
  { key: 'selected',    label: 'Selected'    },
  { key: 'rejected',    label: 'Rejected'    },
];

export const APP_LIMIT = 5;

export const DIFFICULTY_META = {
  Easy:   { color: 'var(--em)',    bg: 'var(--em-dim)',   border: 'rgba(16,185,129,.28)' },
  Medium: { color: 'var(--amber)', bg: 'var(--am-dim)',   border: 'rgba(245,158,11,.28)' },
  Hard:   { color: 'var(--rose)',  bg: 'var(--rose-dim)', border: 'rgba(244,63,94,.28)'  },
};
